import { type NextRequest, NextResponse } from "next/server"
import nodemailer from "nodemailer"

// Email configuration
const SMTP_CONFIG = {
  host: "smtp.gmail.com",
  port: 587,
  secure: false,
  auth: {
    user: "basilmeshack13@gmail.com",
    pass: "tyzmsfhxyipmtyyt",
  },
}

// Sample mental health professionals database
const MENTAL_HEALTH_PROFESSIONALS = [
  {
    name: "Dr. Sarah Johnson",
    email: "dr.sarah.johnson@mentalhealth.com",
    specialty: "Crisis Intervention & Suicide Prevention",
    phone: "+1-555-0123",
    location: "Downtown Mental Health Center",
    availability: "24/7 Emergency Services",
  },
  {
    name: "Dr. Michael Chen",
    email: "dr.michael.chen@therapy.com",
    specialty: "Anxiety & Depression Treatment",
    phone: "+1-555-0456",
    location: "Community Wellness Clinic",
    availability: "Mon-Fri 9AM-6PM, Emergency on-call",
  },
  {
    name: "Dr. Emily Rodriguez",
    email: "dr.emily.rodriguez@crisis.org",
    specialty: "Emergency Mental Health Services",
    phone: "+1-555-0789",
    location: "Crisis Response Center",
    availability: "24/7 Crisis Hotline",
  },
]

export async function POST(request: NextRequest) {
  try {
    const { userEmail, conversationReport, riskLevel, symptoms } = await request.json()

    if (!userEmail || !conversationReport) {
      return NextResponse.json({ error: "Missing required information" }, { status: 400 })
    }

    // Create transporter
    const transporter = nodemailer.createTransporter(SMTP_CONFIG)

    // Select appropriate professional based on risk level
    const professional = MENTAL_HEALTH_PROFESSIONALS[0] // Default to crisis specialist

    // Email to user with professional referral
    const userEmailContent = `
Dear Friend,

Thank you for reaching out and sharing your feelings with our mental health assistant. Your courage in seeking help is commendable, and we want to ensure you receive the professional support you deserve.

Based on our conversation, I'm connecting you with a qualified mental health professional who can provide immediate assistance:

**Professional Referral:**
- **Name:** ${professional.name}
- **Specialty:** ${professional.specialty}
- **Phone:** ${professional.phone}
- **Location:** ${professional.location}
- **Availability:** ${professional.availability}

**Immediate Resources:**
- National Suicide Prevention Lifeline: 988
- Crisis Text Line: Text HOME to 741741
- Emergency Services: 911

**Important Reminders:**
- You are not alone in this struggle
- Professional help is available and effective
- Your life has value and meaning
- Recovery is possible with proper support

Please reach out to the professional above or contact emergency services if you're in immediate danger.

With care and support,
Dr. AI Mental Health Assistant

---
This is an automated referral from our AI mental health support system.
`

    // Email to professional with conversation report
    const professionalEmailContent = `
Subject: URGENT - Mental Health Referral Report

Dear ${professional.name},

This is an automated referral from our AI Mental Health Assistant system. A user has exhibited signs of severe distress and requires immediate professional attention.

**RISK ASSESSMENT:**
- Risk Level: ${riskLevel.toUpperCase()}
- Detected Symptoms: ${symptoms.join(", ") || "None specified"}
- Referral Reason: Crisis intervention needed

**USER CONTACT:**
- Email: ${userEmail}
- Referral Time: ${new Date().toLocaleString()}

**CONVERSATION REPORT:**
${conversationReport}

**RECOMMENDED ACTIONS:**
1. Contact user within 24 hours
2. Assess immediate safety concerns
3. Provide crisis intervention if needed
4. Schedule follow-up appointments
5. Consider emergency services if warranted

**CRISIS RESOURCES:**
- National Suicide Prevention Lifeline: 988
- Crisis Text Line: 741741
- Emergency Services: 911

This referral was generated by our neuro-symbolic AI system that combines rule-based safety detection with machine learning analysis.

Please prioritize this case and provide appropriate professional care.

Best regards,
AI Mental Health Assistant System
Automated Referral Service
`

    // Send email to user
    await transporter.sendMail({
      from: SMTP_CONFIG.auth.user,
      to: userEmail,
      subject: "Mental Health Professional Referral - Support is Available",
      text: userEmailContent,
    })

    // Send email to professional
    await transporter.sendMail({
      from: SMTP_CONFIG.auth.user,
      to: professional.email,
      subject: "URGENT - Mental Health Referral Report",
      text: professionalEmailContent,
    })

    return NextResponse.json({
      success: true,
      professional: {
        name: professional.name,
        phone: professional.phone,
        specialty: professional.specialty,
      },
    })
  } catch (error) {
    console.error("Email sending error:", error)
    return NextResponse.json({ error: "Failed to send referral emails" }, { status: 500 })
  }
}
