// lib/sendReferralEmail.ts
import nodemailer from "nodemailer"

const transporter = nodemailer.createTransport({
  host: process.env.SMTP_HOST,
  port: parseInt(process.env.SMTP_PORT || "587"),
  secure: process.env.SMTP_SECURE === "true",
  auth: {
    user: process.env.SMTP_USER,
    pass: process.env.SMTP_PASSWORD,
  },
})

export interface ReferralDetails {
  userEmail: string
  conversationReport: string
  riskLevel: string
  symptoms: string[]
}

export async function sendReferralEmail({
  userEmail,
  conversationReport,
  riskLevel,
  symptoms,
}: ReferralDetails) {
  const professionalEmail = "bmwandera14@gmail.com"
  const subject = `🚨 Calmi Referral: ${riskLevel.toUpperCase()} Risk Detected`

  const htmlBody = `
    <h2>🚨 New Mental Health Referral from Calmi</h2>
    <p><strong>User Email:</strong> ${userEmail}</p>
    <p><strong>Risk Level:</strong> <span style="color:red;">${riskLevel.toUpperCase()}</span></p>
    <p><strong>Symptoms Detected:</strong> ${symptoms?.length ? symptoms.join(", ") : "None"}</p>
    <h3>🧠 Conversation Report</h3>
    <pre style="white-space:pre-wrap; background:#f5f5f5; padding:1em; border-radius:5px; border:1px solid #ccc;">
${conversationReport}
    </pre>
    <p style="font-size:12px; color:gray;">This referral was automatically generated by the Calmi AI Mental Health Assistant for further human intervention.</p>
  `

  try {
    await transporter.sendMail({
      from: process.env.SMTP_FROM || `"Calmi AI" <noreply@calmi.ai>`,
      to: professionalEmail,
      subject,
      html: htmlBody,
    })

    return {
      success: true,
      professional: {
        name: "Dr. Vincent Wandera",
        specialty: "Licensed Clinical Psychologist",
        phone: "+254 712 345678",
        email: professionalEmail,
      },
    }
  } catch (error) {
    console.error("❌ Email sending failed:", error)
    return { success: false, error }
  }
}
